name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools poetry wheel
          poetry install

      - name: Build project
        run: |
          python setup.py sdist bdist_wheel
  
  test:
    needs: build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install setuptools poetry  
          poetry install --with dev

      - name: Run unit tests
        run: poetry run pytest

      - name: Run rfbrowser init
        run: poetry run rfbrowser init

      - name: Run acceptance tests
        run: poetry run robot -d Logs atest/testcases
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./Logs
          name: robot-test-results-${{ matrix.python-version }}
          retention-days: 3