name: Test

on:
    workflow_run:
      workflows: ["Build"]
      types:
        - completed
  

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install poetry  
          poetry install --with dev

      - name: Run unit tests
        run: poetry run pytest

      - name: Run rfbrowser init
        run: poetry run rfbrowser init

      - name: Run acceptance tests
        run: poetry run robot atest/testcases
